document.write("            <div class=\"info\">");
document.write("                <div class=\"programms\">");
document.write("                    <h1>ΠΡΟΓΡΑΜΜΑΤΑ ΞΕΝΩΝ ΓΛΩΣΣΩΝ<\/h1>");
document.write("                    -----------------------------------------------");
document.write("                    <p>");
document.write("                        <a href=\"\/offers\/offers.html\">Γενικές Προσφορές<\/a>");
document.write("                    <\/p>");
document.write("                    <p>");
document.write("                        <a href=\"\/offers\/offers.html\">Προσφορές για φοιτητές<\/a>");
document.write("                    <\/p>");
document.write("                    <p>");
document.write("                        <a href=\"\/offers\/offers.html\">Προσφορές για ενήλικες<\/a>");
document.write("                    <\/p>");
document.write("        ");
document.write("                <\/div>");
document.write("<div class=\"information\">");
document.write("<h1>ΒΡΕΙΤΕ ΜΑΣ<h1>");
document.write("-----------------------------------------");
document.write("<p class=\"location\">");
document.write("<img class=\"loc\" src=\"\/icons\/locationIcon.png\" alt=\"location\">");
document.write("  Διεύθυνση: Κ. Καρτάλη 127 με Γαλλίας<\/p>");
document.write("<p class=\"email\">");
document.write("<img class=\"em\" src=\"\/icons\/emailIcon.png\" alt=\"email\">");
document.write("  Email: xenoglossipaideia@gmail.com<\/p>");
document.write("<p class=\"phone\">");
document.write("<img class=\"ph\" src=\"\/icons\/phoneIcon.png\" alt=\"phone\">");
document.write("  Τηλέφωνο: 24210 31162 <br> Κιν: 6909388578<\/p>");
document.write("");
document.write("<\/div>");
document.write("<br>");
document.write("<div class=\"copy\">");
document.write("                <p>Copyright &copy; 2020  Ξενόγλωσση παιδεία - Φροντιστήρια Ξένων Γλωσσών Βόλος - Κέντρα Ξένων Γλωσσών<\/p>");
document.write("            <\/div>");
document.write("<\/div>");